runtime: python310
automatic_scaling:
  target_cpu_utilization: 0.90
  max_instances: 1
entrypoint: gunicorn -b :8080 app:server
env_variables:
  BUCKET_NAME: 'cs122-group5.appspot.com'
  USE_GCS: '1'